export const MAIN_URL =  'https://electionsapi.softmastersgroup.com/';
export const APIKEY = "BiSJjJkaWB";
export const TOKEN_URL = MAIN_URL + 'token';
export const LOGIN_URL = MAIN_URL +'login/verifytelephone';
export const REGISTRATION_URL = MAIN_URL + 'register';
export const SUBMIT_INCIDENT = MAIN_URL + 'incident/add';
export const POLLING_STATION = MAIN_URL + 'ballot/polligstations';
export const POLLING_SEARCH = MAIN_URL + 'ballot/searchpolling';
export const VERIFY_DEVICE = MAIN_URL +'login/verifydevice';
